### ISSUE TITLE
Incorrect documentation regarding version constraints on dependencies

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#2723]
**Problem:**

The [documentation](https://docs.inmanta.com/community/latest/model_developers/modules.html#module-metadata) says version constraints on the dependencies of a module, should be set in the following way:

```
license: Apache 2.0
name: ip
source: git@github.com:inmanta/ip
version: 0.1.15
requires:
    net: net ~= 0.2.4
    std: std >1.0 <2.5
```

This is incorrect, since the version constraint should added as a list instead of a dictionary.

```
license: Apache 2.0
name: ip
source: git@github.com:inmanta/ip
version: 0.1.15
requires:
    - net ~= 0.2.4
    - std >1.0 <2.5
```

When the incorrect notation is used, the version constraints are ignored, but it doesn't result in a compilation error.

**Tasks:**

- [x] Update the documentation as such that it correctly describes the use of `requires` entry.
- [ ] Ensure that all inmanta tools validate the `module.yml` file against the expected schema and report an error when the given `module.yml` file is not in line with the schema.
