### ISSUE TITLE
Modules V2 - Docs

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#3023]
- When documenting Modules V2, add notes that these features are under development, that we can later remove. 
- [ ] Update modules.rst to explain both module formats 
- [ ] Update release.rst to explain that we have two ways of distributing, explain both
- [ ] Update `reference/projectyml.rst` to also show how this looks as 'yaml' (now it shows python only, may be hard to understand for some people)
- [ ] Update `reference/projectyml.rst` (by updating the `inmanta.module.ProjectMetadata`) to also be able to point to pypi indexes.

``` yaml
repos:
  - https://github.com/inmanta/
  - url: https://github.com/inmanta/
    type: git
  - url: https://pypi.org/simple/
    type: pypi
```
